# Generated by Django 3.1.7 on 2021-03-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_id', models.IntegerField(default=0)),
                ('screen_name', models.CharField(max_length=150)),
                ('created_at', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=5)),
                ('covid_time', models.IntegerField(default=9)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_Handles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=150)),
                ('twitter_handle', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=150)),
            ],
        ),
    ]
