# Generated by Django 3.1.7 on 2021-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foot_tweet_app', '0002_auto_20210312_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=150)),
                ('screen_name', models.CharField(max_length=150)),
                ('created_at', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=500)),
                ('covid_time', models.IntegerField(default=9)),
                ('sentiment', models.CharField(max_length=15)),
            ],
        ),
    ]
