# Generated by Django 3.1.7 on 2021-04-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foot_tweet_app', '0005_twitter_handles_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='handle_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
