# Generated by Django 3.1.7 on 2021-04-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foot_tweet_app', '0006_auto_20210414_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='cleaned_tweet',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(max_length=1000),
        ),
    ]
